variables:
    https_proxy: www-proxy-ash7.us.oracle.com:80
    no_proxy: .oraclecorp.com
build:
  script:
    - git clone https://github.com/oracle/learning-library.git
    - git status
    - git config --global user.email "doceng-alm_ww@oracle.com"
    - git config --global user.name "DocEng Admin"
    #- git remote add livelabs-sync https://gitlab.hap.demo.us-phoenix-1.oci.oraclecloud.com/luna-labs/docs/test-remote.git
    #- git remote -v
    - cp -pr learning-library/oci-library/oci-hol/deploying-jenkins learning-library/oci-library/oci-hol/oci-private-dns learning-library/oci-library/oci-hol/auditing-in-autonomous-database learning-library/oci-library/oci-hol/compute-service .
    - rm -rf learning-library
    - pwd
    - ls -ltr
    - git add . && git commit -m "OCI Learning Library from GitHub"
    - git push origin master